### ISSUE TITLE
Controller Name PLEASE

### ISSUE THREAD

**Issue by VTXSRB** [lythx/trakman#131]
preferably we want an actual name other than "TRAKMAN" (not saying it's bad)
suggest anything that comes to your mind, acronyms are preferred but not a must.

**Some words you could potentially use:
Controller
Mania
TypeScript (TS)**

what we have so far:
NAME (New Age Mania Evolution)
CORE (Controller Redux)
SCORE (Script Controller Redux)

tx

**Comment by wsrvn** [comment]
what!!!

**Comment by VTXSRB** [comment]
WHO THE FUCK SENT ME THIS SHIT BRUH

**Comment by helldevil666** [comment]
guys remember that i still own 20% of your net worth, without my input the
controller would never exist
