### ISSUE TITLE
adding a map that is already present destroys the server queue

### ISSUE THREAD

**Issue by wsrvn** [lythx/trakman#186]
using //add to queue a tmx map breaks the server map list entirely if the said map was already on the server. 

in this case, the "ChooseNextChallenge" call always responds with an error stating "challenge is not in the selection", despite the map being present in both the database and the matchsettings file.

the filepaths in either also match, thus eliminating file mismatch as the culprit.

main issue here is the inability to ever queue the map in question, even after the controller restart. the error will keep reappearing until you shutdown and relaunch the dedicated server entirely, therefore this might not be our bug at all.

**Comment by VTXSRB** [comment]
😕
