### ISSUE TITLE
Dedimania on TMUF

### ISSUE THREAD

**Issue by Skorlok** [lythx/trakman#190]
Yo,

After trying this controller on TMUF (snow server)

I have this error:
`<ERROR> [19 Feb 2023 21:28:18] (Dedimania.js:111) Failed to fetch dedimania records for map Snow 2011 Lolly Jump (eY8soznlJRerRcKFVWvUfZvLXni), received error:
Dedimania server responded with an error Error in method_handler.php(926): Invalid Environment: TMU,Snow Code: 
`
that all

**Comment by Skorlok** [comment]
It works when i hardcode it:
./built/plugins/dedimania/Dedimania.js:87

replacing 
`{ string: environment },`
with
`{ string: 'Alpine' },`

the error is the parameter sent to the function getRecords (id, name, **_ENVIRONMENT_**, author)

**Comment by lythx** [comment]
> It works when i hardcode it: ./built/plugins/dedimania/Dedimania.js:87
> 
> replacing `{ string: environment },` with `{ string: 'Alpine' },`
> 
> the error is the parameter sent to the function getRecords (id, name, **_ENVIRONMENT_**, author)

Ah its 'Snow' instead of 'Alpine' in the controller, will fix in the next version thank you

**Comment by wsrvn** [comment]
should be fixed on main rn, if you find any more united related bugs would be nice if you reported them on here
