### ISSUE TITLE
Missing xaseco feautures

### ISSUE THREAD

**Issue by ExEric3** [lythx/trakman#199]
Hia,

is planned musicserver and forcemods implementation? Also add some discord ingame button.

**Comment by lythx** [comment]
For forcemods go to plugins/ui/config/Mod.js and set the modUrl property, musicserver and discord server will be added in the next version (1.3) 🍩

**Comment by wsrvn** [comment]
if by music server you mean custom music on the server then it can be done otherwise idk join me on krunker

**Comment by ExEric3** [comment]
And that forcemods can be random? More loadscreens on stadium I want.

**Comment by lythx** [comment]
No forcemods can't be random for now. I can make an option to randomize it but that might cause some issues like mods not loading for some players

**Comment by ExEric3** [comment]
Will wait for v1.3 then. Thanks
