### ISSUE TITLE
Server links

### ISSUE THREAD

**Issue by ExEric3** [lythx/trakman#200]
Hia,

is planned something like zeroswitch or server neighborhood?

**Comment by lythx** [comment]
Should be easy to make I'll do it for the next version probably

**Comment by ExEric3** [comment]
Okey thanks.

**Comment by wsrvn** [comment]
no need to close, we will do it automatically whenever the necessary commits are merged into main. same applies for #199.

**Comment by VTXSRB** [comment]
200TH ISSUE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
