### ISSUE TITLE
controller hanging unexpectedly with no error present

### ISSUE THREAD

**Issue by wsrvn** [lythx/trakman#207]
happened at least 4 times on loltards, it is reproducible in daemon mode (npm run daemon), but not in normal launch mode (npm run start). no error is output in the log, so debuggin is impossible idk how to fix

**Comment by wsrvn** [comment]
lies lies lies! no new version until this is fixed!!

**Comment by wsrvn** [comment]
this is still not fixed i dont even know at this point

**Comment by lythx** [comment]
very bad

**Comment by wsrvn** [comment]
#214
