### ISSUE TITLE
on the very first start, a ton of database errors pop up

### ISSUE THREAD

**Issue by wsrvn** [lythx/trakman#210]
initially reported in #208, but known for quite some time: on the very first controller start, you will encounter a plethora of database errors that are related to operations executing in parallel.

quoting my friend @lythx: 
>fixing it would be insanely cancer
>cuz
>we purposefully dont await some actions as they take time on launch
>but when the db gets created theres just too many calls and delay is too big
>so it crashes

you could always restart a few times tho..

**Comment by VTXSRB** [comment]
Can You Mention This Issue Again

**Comment by wsrvn** [comment]
#210

**Comment by VTXSRB** [comment]
One More Time Please !

**Comment by wsrvn** [comment]
cant reproduce with node 21.4.0 and psql 16.1, assuming its fixed
