### ISSUE TITLE
Maplist not reloaded after adding maps with external tool

### ISSUE THREAD

**Issue by Skorlok** [lythx/trakman#212]
Hi,
just a little feature suggestion:
I would like to easily add maps from Adminserv or my discord bot without restart the controller

Just need to reload the maplist on "TrackMania.ChallengeListModified" callback (src/Listeners.ts)

**Comment by wsrvn** [comment]
can be buggy in specific cases, we'll be testing this soon

**Comment by lythx** [comment]
The feature is on the dev branch for now (gonna be on main today probably). I tested it by executing commands from controller code, hopefully it works with your tools too

**Comment by lythx** [comment]
To enable it set "updateMatchSettingsOnChange" to true in the main controller config (/config/Config.js)

**Comment by lythx** [comment]
merged to main
