### ISSUE TITLE
Please create a Video explain how install & configure!

### ISSUE THREAD

**Issue by Janzhx** [lythx/trakman#215]
Hello, I wanted to congratulate you on the plugin, it looks very good, it's a shame that it doesn't explain very well how to configure it in Windows, it would be a very good idea if you create a complete, well-explained video.
I would like to test it on my TMNF server. Greetings

**Comment by VTXSRB** [comment]
The video was made, I just always forget to upload it lol. I'll do it today (probably)

**Comment by Janzhx** [comment]
ok nice😃, let's hope that the content leads to a successful configuration, and so come and acknowledge it, we'll be waiting for the video, regards.

**Comment by Janzhx** [comment]
Hello, Video please! To make your answer complete, please upload an explanatory and complete video, because not everything is done randomly

**Comment by VTXSRB** [comment]
Hehe 😋😊😊😊 smiling ☺️☺️☺️😊😊 the video ☺️📸📸📸 the same price as the rendered replays on my mask 😷😷😷 to do with it I don't know if you will have any money 💰🤑💰💰🤑💰🤑💰🤑 i ii i i i i i  d d to buy the house 🏠🏠🏠🏠🏠🏠 the video 📷📷📷📷📷

Here's The Video 📸🎥

[The Video](https://www.youtube.com/watch?v=hvU5nx0tr5A)

**Comment by wsrvn** [comment]
i have no way of recording the windows installation instructions on my linux desktop.
