### ISSUE TITLE
Its possible to change the bill login?

### ISSUE THREAD

**Issue by Loomer2** [lythx/trakman#216]
Hello ¡Well Done!, I installed it out of curiosity in beta mode on windows, now I want to know if it is possible to change the "payout coopers" login to receive donations from coopers, take action skip map, replay map for my same account in which I play and not from the server login, since it cannot be used!! and that it is not the same as that
Can i change it in the root files? 

I await your response, maybe it's hidden there  (?=

**Comment by wsrvn** [comment]
it is possible as all payments go through the same method. if you want to change it, edit this line (270) in /src/Utils.ts

https://github.com/lythx/trakman/blob/7ca9c46a18e4e002c340ea3ba40e7e8f120c7305/src/Utils.ts#L270

switch `targetLogin: string = ''` for `targetLogin: string = 'your_tm_login'`
after that, rebuild and launch again, the controller will then send bills with your login as the one receiving coppers.

**Comment by Loomer2** [comment]
Thank you very much for your attention, but I have changed the indicated line 270 targetLogin: string = ''MY LOGIN" targetLogin: string = 'your_tm_login'

restart npm run stop & npm run daemon(background) and it didn't work, any other ideas?
