### ISSUE TITLE
Comments section in file Buttons.js missing mention about background property

### ISSUE THREAD

**Issue by xadll** [lythx/trakman#231]
https://github.com/lythx/trakman/blob/fc8d4b0bdbdf74464eaeb0f6638bf9c3c171789c/plugins/ui/config/Buttons.js#L76C7-L76C17

**Comment by wsrvn** [comment]
https://github.com/lythx/trakman/blob/fc8d4b0bdbdf74464eaeb0f6638bf9c3c171789c/plugins/ui/config/ResultUi.js#L8
