### ISSUE TITLE
//shuffle command wipe the queue

### ISSUE THREAD

**Issue by xadll** [lythx/trakman#235]

**Comment by wsrvn** [comment]
it is assumed you dont care about the queue if you do shuffle

**Comment by xadll** [comment]
> it is assumed you dont care about the queue if you do shuffle

OK then I misunderstood.
I thought that according to the description the command shuffles the maps in the queue (jukebox).

**Comment by xadll** [comment]
> > it is assumed you dont care about the queue if you do shuffle
> 
> I thought that, according to the description, the command shuffles positions of the queued maps in the queue (jukebox). OK, then the help is misleading.
> 
> https://github.com/lythx/trakman/blob/fc8d4b0bdbdf74464eaeb0f6638bf9c3c171789c/plugins/commands/config/JukeboxCommands.config.js#L25

So, I recommend changing the description to **Shuffle the map list.**
