### ISSUE TITLE
Querying TMX for certain author

### ISSUE THREAD

**Issue by AroPix** [lythx/trakman#238]
With Xaseco there was the possibility to query for a certain author, as example:
/xlist auth:nadeo, to get all TMX tracks uploaded by Nadeo.
This function doesn't exist yet in trakman apparently (i was talking to wise and he told me to open a issue, so i'm requesting this as a feature.

**Comment by wsrvn** [comment]
22ad49a, e.g.: ```/xlist $a aropix```. due to new tmx api limitations only full author names are supported (weird stuff from them imo)
