### ISSUE TITLE
some TypeError about invalid url

### ISSUE THREAD

**Issue by thecoolkidz102** [lythx/trakman#241]
im not sure what to do here, pls help
![image](https://github.com/lythx/trakman/assets/156242948/cff3e580-1581-421d-954e-177a83d59077)

**Comment by Chris92de** [comment]
Most likely this error means you didn't configure the `DISCORD_WEBHOOK_URL` in the config properly. Either set `DISCORD_LOG_ENABLE` to `False` or add a valid Discord Webhook URL in your .env file.

**Comment by thecoolkidz102** [comment]
t

**Comment by wsrvn** [comment]
will change the .env.example to no by default i guess
