### ISSUE TITLE
Question / The philosophy of counting stats (TopSums, TopRecords and TopVotes)

### ISSUE THREAD

**Issue by xadll** [lythx/trakman#246]
I think XAseco calculated stats from all maps including those from the past, the same way Trakman do, but that always seemed odd to me.
Is there something important behind it that I'm missing?

Should these stats also be calculated from maps that have been played in the past but are no longer physically in the maplist?
I like the opposite idea - show statistics calculated from the current maplist only.
What is your opinion?

## Stats of top 3 players when currently only 2 maps are on maplist

![20240121_175429-131](https://github.com/lythx/trakman/assets/17713868/83396fc3-b5b4-4df7-bdaf-ccaac330d8a4)
![20240121_175424-976](https://github.com/lythx/trakman/assets/17713868/8cb9daf7-9f3c-4bdb-9146-d74f241ab77d)
![20240121_175310-063](https://github.com/lythx/trakman/assets/17713868/c9816e00-e774-439e-bb22-7703045125a5)

**Comment by wsrvn** [comment]
this is a bug in our code, stats should only be calculated using the current maplist

**Comment by wsrvn** [comment]
should be fixed via 67ed889
