### ISSUE TITLE
When to exit the process

### ISSUE THREAD

**Issue by lythx** [lythx/trakman#51]
Since we don't want unnecessary crashes (which happen in xaseco quite often as far as i know), we should think about on which errors the process should be exited. Obviously there are cases when controller needs to crash such as error in initializing services or losing connection with the server on socket, however exiting process on every failed database query or client call seems unnecessary (especially considering that external plugins irrelevant to core contoller functionality may use these methods). My suggestion is that in methods like these instead of throwing right away we just log the error and then return it. That would allow us to check for error on method call and then decide if we throw the program or not. For example if 'authorize' call in main retuns error we throw because there is no sense in continuing, but if a 'displayManialink' call from a plugin returns error we just log it since server can run without it. Maybe theres some better way  to do it tho, also it would be nice to hear from our expert mr. Waseraven about what caused most crashes in XASECO cuz we might run into similar problems

**Comment by VTXSRB** [comment]
vlofdr thidf iddure
